import java.util.ArrayList;

public class adder {
    adder( ArrayList<Personne> personnes){
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
        personnes.add(new Personne("not Doe", "John", 30));
        personnes.add(new Personne("Doe", "not not Jane", 25));
        personnes.add(new Personne("Doe", "not John", 30));
    }
}
